version: "3"
services:

    eureka:
      image: "lreimer/cloud-native-eureka"
      ports:
        - "8761:8761"
      networks:
        - backend

    config-server:
      image: "lreimer/cloud-native-config"
      depends_on:
        - eureka
      environment:
        EUREKA_HOST: eureka
        EUREKA_PORT: 8761
      ports:
        - "8888:8888"
      networks:
        - backend

    zuul:
      image: "lreimer/cloud-native-zuul"
      depends_on:
        - eureka
        - config-server
      environment:
        EUREKA_HOST: eureka
        EUREKA_PORT: 8761
      ports:
        - "8765:8765"
      networks:
        - backend

    cloud-native-basta17:
      build: .
      image: "cloud-native-basta17"
      command: --server.urls http://0.0.0.0:5000
      environment:
        EUREKA_HOST: eureka
        EUREKA_PORT: 8761
      depends_on:
        - eureka
        - config-server
      ports:
        - "5000:5000"
      networks:
        - backend

networks:
  backend:
