apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  ports:
  - port: 8761
  selector:
    app: eureka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: "lreimer/cloud-native-eureka"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8761
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8761
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  type: NodePort
  ports:
  - port: 8888
  selector:
    app: config-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: "lreimer/cloud-native-config"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8888
          initialDelaySeconds: 90
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8888
          timeoutSeconds: 30
        env:
        - name: EUREKA_HOST
          value: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native-basta17
  labels:
    app: cloud-native-basta17
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    app: cloud-native-basta17
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-native-basta17
spec:
  replicas: 2
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: cloud-native-basta17
    spec:
      containers:
      - name: cloud-native-basta17
        image: "lreimer/cloud-native-basta17"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 5000
          timeoutSeconds: 10
        env:
        - name: EUREKA_HOST
          value: eureka